### ISSUE TITLE
Synthetic events don't have `stopImmediatePropagation`

### ISSUE THREAD

**Issue by back2dos** [MVCoconut/coconut.react-dom#1]
Accessing it should fail at compile time.

**Comment by kevinresol** [comment]
just happen I am looking for the definition for `SyntheticEvent`. It doesn't seem to exist in react-next? @klabz

**Comment by kLabz** [comment]
I have some things in react-types but I didn't really use them so I'm not sure what they're worth

**Comment by back2dos** [comment]
I've chosen to make it proxy to `stopPropagation` for better portability from coconut.vdom to coconut.react-dom
