### ISSUE TITLE
Inline markup not working with latest react-next

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.react-dom#2]
Code here: https://github.com/MVCoconut/mvcoconut.github.io/blob/882508f/demo/src/App.hx
Compile with `coconut.react-dom`

Inline markup in `render()` doesn't work, but string does.

It will complain with `src/App.hx:15: characters 7-13 : Missing return: coconut.ui.RenderResult`

**Comment by kevinresol** [comment]
I have a situation here:

1. because of this issue my react-next is staying at v1.108.1
1. I need nightly Haxe to fix [the hang](https://github.com/HaxeFoundation/haxe/issues/8043)
1. but react-next v1.108.1 fails with `/Users/kevin/haxe/haxe_libraries/react-next/1.108.1/github/b23a99d3d88f77dd90c2af754aa76361e05e48ad/src/lib/react/jsx/HtmlEntities.hx:4: character 63 : Invalid escape sequence \u. UTF-16 surrogates are not allowed in strings.`
1. upgrading react-next to latest give me error `string constant expected`

@back2dos @klabz can you have a look?

**Comment by kLabz** [comment]
Latest git or latest haxelib for react-next?

Edit:
Nevermind, I just realised I released 1.115.0 so they're the same.

**Comment by kevinresol** [comment]
Latest haxelib

**Comment by kLabz** [comment]
Can you try with `-D react_no_auto_jsx`? (I guess I should make it opt-in rather than opt-out, didn't think it would create some conflict with coconut)

**Comment by kevinresol** [comment]
yeah that works

**Comment by kevinresol** [comment]
I think we can define it in coconut's `extraParams.hxml`

**Comment by kLabz** [comment]
I think I'll change this to opt-in (with `-D react_auto_jsx`) anyway, it does seem like having this feature without being aware of it can cause some confusion and issues.

**Comment by kevinresol** [comment]
okay

**Comment by kLabz** [comment]
Done in `1.116.0`.
