### ISSUE TITLE
Issue with background-image style

### ISSUE THREAD

**Issue by Neverbirth** [MVCoconut/coconut.react-dom#7]
Having in coconut react something like `<div style={'background-image: url(${myImageUrl})'}` results in react development complaining with

>Warning: Unsupported style property background-image. Did you mean backgroundImage?

However changing it to `backgroundImage` is not working because `tink.domspec.CSSParser.parseString` is not liking it, I confirmed that making the function return `bacgroundImage` is working and gets rid of the warning. Is there any workaround for this or is it some bug requiring to do code changes?

**Comment by kevinresol** [comment]
I think string style parsing is deprecated. You should use an object instead. `style={{backgroundImage: 'url(${myImageUrl})'}}`

**Comment by Neverbirth** [comment]
Confirming it works. Nice, I didn’t know of it. I still have some React warning about setState being called with the component not being mounted, but I haven’t seen yet any indication of where it comes from.

**Comment by back2dos** [comment]
Well, it's not really deprecated, but currently it

**Comment by back2dos** [comment]
The current string parsing solution exist primarily so that one can just copy-paste inline HTML, but pushes a lot of work into the runtime. Ultimately it should be make to work, or at least clearly warn.

**Comment by back2dos** [comment]
This works now and gives an appropriate warning.
